name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ocelot.aperture.akron.oh.us
          username: coblabs
          key: ${{ secrets.OCELOT_SSH_WWW }}
          script: echo "Deploying..."
